twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        google_key: '%env(GOOGLE_KEY)%'
        paypal_id: '%env(PAYPAL_ID)%'
        minimum_order_price: '%env(MINIMUM_ORDER_PRICE)%'
        price_of_care: '%env(PRICE_OF_CARE)%'
        price_per_km: '%env(PRICE_PER_KM)%'
        price_per_minute: '%env(PRICE_PER_MINUTE)%'

when@test:
    twig:
        strict_variables: true
