twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        google_key: '%env(GOOGLE_KEY)%'
        paypal_id: '%env(PAYPAL_ID)%'

when@test:
    twig:
        strict_variables: true
